version: "2"

run:
  concurrency: 4
  tests: false
  modules-download-mode: readonly

output:
  formats:
    text:
      colors: true
      print-issued-lines: true
      print-linter-name: true
      path: stdout

linters:
  enable:
    - errcheck
    - forbidigo
    - staticcheck
    - govet
    - exhaustive
    - ineffassign
    - misspell
    - unparam
    - unused
    - iface
    - importas
    - goconst
    - testifylint
    - whitespace

  settings:
    forbidigo:
      forbid:
        - pattern: ^fmt\.Print(f|ln)?$
    misspell:
      locale: US
    unparam:
      check-exported: false
    prealloc:
      simple: true
      range-loops: true
      for-loops: true

  exclusions:
    rules:
      - linters:
          - errcheck
        source: "^\\s*defer\\s+"

formatters:
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
        - pattern: 'a[b:len(a)]'
          replacement: 'a[b:]'

    goimports:
      local-prefixes:
        - github.com/coro-sh/coro