// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: count.sql

package sqlc

import (
	"context"
)

const countNamespaceOperators = `-- name: CountNamespaceOperators :one
SELECT COUNT(*)::BIGINT
FROM operator o
WHERE o.namespace_id = $1
`

func (q *Queries) CountNamespaceOperators(ctx context.Context, namespaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countNamespaceOperators, namespaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOperatorAccounts = `-- name: CountOperatorAccounts :one
SELECT COUNT(*)::BIGINT
FROM account a
WHERE a.operator_id = $1
  AND a.name != 'SYS'
`

func (q *Queries) CountOperatorAccounts(ctx context.Context, operatorID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOperatorAccounts, operatorID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOperatorUsers = `-- name: CountOperatorUsers :one
SELECT COUNT(*)::BIGINT
FROM "user" u
WHERE u.operator_id = $1
  AND u.name != 'sys'
`

func (q *Queries) CountOperatorUsers(ctx context.Context, operatorID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOperatorUsers, operatorID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwnerNamespaces = `-- name: CountOwnerNamespaces :one
SELECT COUNT(*)::BIGINT
FROM namespace AS n
WHERE n.owner = $1
`

func (q *Queries) CountOwnerNamespaces(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerNamespaces, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
