// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: namespace.sql

package sqlc

import (
	"context"
)

const batchReadNamespaces = `-- name: BatchReadNamespaces :many
SELECT id, name, owner
FROM namespace
WHERE id = ANY ($1::text[])
`

func (q *Queries) BatchReadNamespaces(ctx context.Context, ids []string) ([]*Namespace, error) {
	rows, err := q.db.Query(ctx, batchReadNamespaces, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(&i.ID, &i.Name, &i.Owner); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNamespace = `-- name: CreateNamespace :exec
INSERT INTO namespace (id, name, owner)
VALUES ($1, $2, $3)
`

type CreateNamespaceParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Owner string `json:"owner"`
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error {
	_, err := q.db.Exec(ctx, createNamespace, arg.ID, arg.Name, arg.Owner)
	return err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
SELECT delete_namespace_and_nkeys($1)
`

func (q *Queries) DeleteNamespace(ctx context.Context, nsID string) error {
	_, err := q.db.Exec(ctx, deleteNamespace, nsID)
	return err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, name, owner
FROM namespace
WHERE ($2::TEXT IS NULL OR id <= $2::TEXT)
  AND owner = $1
ORDER BY id DESC
LIMIT $3
`

type ListNamespacesParams struct {
	Owner  string  `json:"owner"`
	Cursor *string `json:"cursor"`
	Size   int32   `json:"size"`
}

func (q *Queries) ListNamespaces(ctx context.Context, arg ListNamespacesParams) ([]*Namespace, error) {
	rows, err := q.db.Query(ctx, listNamespaces, arg.Owner, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(&i.ID, &i.Name, &i.Owner); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readNamespace = `-- name: ReadNamespace :one
SELECT id, name, owner
FROM namespace
WHERE id = $1
`

func (q *Queries) ReadNamespace(ctx context.Context, id string) (*Namespace, error) {
	row := q.db.QueryRow(ctx, readNamespace, id)
	var i Namespace
	err := row.Scan(&i.ID, &i.Name, &i.Owner)
	return &i, err
}

const readNamespaceByName = `-- name: ReadNamespaceByName :one
SELECT id, name, owner
FROM namespace
WHERE name = $1
  AND owner = $2
`

type ReadNamespaceByNameParams struct {
	Name  string `json:"name"`
	Owner string `json:"owner"`
}

func (q *Queries) ReadNamespaceByName(ctx context.Context, arg ReadNamespaceByNameParams) (*Namespace, error) {
	row := q.db.QueryRow(ctx, readNamespaceByName, arg.Name, arg.Owner)
	var i Namespace
	err := row.Scan(&i.ID, &i.Name, &i.Owner)
	return &i, err
}
