// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: owner.sql

package sqlc

import (
	"context"
)

const countOwnerAccounts = `-- name: CountOwnerAccounts :one
SELECT COUNT(*)::BIGINT
FROM account a
         JOIN namespace n ON n.id = a.namespace_id
WHERE n.owner = $1
`

func (q *Queries) CountOwnerAccounts(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerAccounts, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwnerNamespaces = `-- name: CountOwnerNamespaces :one
SELECT COUNT(*)::BIGINT
FROM namespace AS n
WHERE n.owner = $1
`

func (q *Queries) CountOwnerNamespaces(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerNamespaces, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwnerOperators = `-- name: CountOwnerOperators :one
SELECT COUNT(*)::BIGINT
FROM operator o
         JOIN namespace n ON n.id = o.namespace_id
WHERE n.owner = $1
`

func (q *Queries) CountOwnerOperators(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerOperators, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countOwnerUsers = `-- name: CountOwnerUsers :one
SELECT COUNT(*)::BIGINT
FROM "user" u
         JOIN namespace n ON n.id = u.namespace_id
WHERE n.owner = $1
`

func (q *Queries) CountOwnerUsers(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnerUsers, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
