// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: count.sql

package sqlc

import (
	"context"
)

const countNamespaceOperators = `-- name: CountNamespaceOperators :one
SELECT COUNT(*) AS count
FROM operator AS o
WHERE o.namespace_id = ?
`

func (q *Queries) CountNamespaceOperators(ctx context.Context, namespaceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNamespaceOperators, namespaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOperatorAccounts = `-- name: CountOperatorAccounts :one
SELECT COUNT(*) AS count
FROM account AS a
WHERE a.operator_id = ?
  AND a.name != 'SYS'
`

func (q *Queries) CountOperatorAccounts(ctx context.Context, operatorID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorAccounts, operatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOperatorUsers = `-- name: CountOperatorUsers :one
SELECT COUNT(*) AS count
FROM "user" AS u
WHERE u.operator_id = ?
  AND u.name != 'sys'
`

func (q *Queries) CountOperatorUsers(ctx context.Context, operatorID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOperatorUsers, operatorID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnerNamespaces = `-- name: CountOwnerNamespaces :one
SELECT COUNT(*) AS count
FROM namespace AS n
WHERE n.owner = ?
`

func (q *Queries) CountOwnerNamespaces(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerNamespaces, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnerOperators = `-- name: CountOwnerOperators :one
SELECT COUNT(*) AS count
FROM operator AS o
         JOIN namespace AS n ON n.id = o.namespace_id
WHERE n.owner = ?
`

func (q *Queries) CountOwnerOperators(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerOperators, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}
