// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

type Account struct {
	ID              string
	NamespaceID     string
	OperatorID      string
	Name            string
	PublicKey       string
	Jwt             string
	UserJwtDuration *int64
}

type Namespace struct {
	ID   string
	Name string
}

type Nkey struct {
	ID   string
	Type string
	Seed []byte
}

type Operator struct {
	ID          string
	NamespaceID string
	Name        string
	PublicKey   string
	Jwt         string
}

type OperatorToken struct {
	OperatorID string
	Type       string
	Token      string
}

type SigningKey struct {
	ID   string
	Type string
	Seed []byte
}

type User struct {
	ID          string
	NamespaceID string
	OperatorID  string
	AccountID   string
	Name        string
	Jwt         string
	JwtDuration *int64
}

type UserJwtIssuance struct {
	UserID     string
	IssueTime  int64
	ExpireTime int64
}
