// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: namespace.sql

package sqlc

import (
	"context"
	"strings"
)

const batchReadNamespaces = `-- name: BatchReadNamespaces :many
SELECT id, name, owner
FROM namespace
WHERE id IN (/*SLICE:ids*/?)
`

func (q *Queries) BatchReadNamespaces(ctx context.Context, ids []string) ([]*Namespace, error) {
	query := batchReadNamespaces
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(&i.ID, &i.Name, &i.Owner); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createNamespace = `-- name: CreateNamespace :exec
INSERT INTO namespace (id, name, owner)
VALUES (?1, ?2, ?3)
`

type CreateNamespaceParams struct {
	ID    string
	Name  string
	Owner string
}

func (q *Queries) CreateNamespace(ctx context.Context, arg CreateNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, createNamespace, arg.ID, arg.Name, arg.Owner)
	return err
}

const deleteNamespace = `-- name: DeleteNamespace :exec
DELETE
FROM namespace
WHERE id = ?1
`

func (q *Queries) DeleteNamespace(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNamespace, id)
	return err
}

const listNamespaces = `-- name: ListNamespaces :many
SELECT id, name, owner
FROM namespace
WHERE (?2 IS NULL OR id <= ?2)
  AND owner = ?1
ORDER BY id DESC
LIMIT ?3
`

type ListNamespacesParams struct {
	Owner  string
	Cursor interface{}
	Size   int64
}

func (q *Queries) ListNamespaces(ctx context.Context, arg ListNamespacesParams) ([]*Namespace, error) {
	rows, err := q.db.QueryContext(ctx, listNamespaces, arg.Owner, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Namespace
	for rows.Next() {
		var i Namespace
		if err := rows.Scan(&i.ID, &i.Name, &i.Owner); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readNamespace = `-- name: ReadNamespace :one
SELECT id, name, owner
FROM namespace
WHERE id = ?1
`

func (q *Queries) ReadNamespace(ctx context.Context, id string) (*Namespace, error) {
	row := q.db.QueryRowContext(ctx, readNamespace, id)
	var i Namespace
	err := row.Scan(&i.ID, &i.Name, &i.Owner)
	return &i, err
}

const readNamespaceByName = `-- name: ReadNamespaceByName :one
SELECT id, name, owner
FROM namespace
WHERE name = ?1
  AND owner = ?2
`

type ReadNamespaceByNameParams struct {
	Name  string
	Owner string
}

func (q *Queries) ReadNamespaceByName(ctx context.Context, arg ReadNamespaceByNameParams) (*Namespace, error) {
	row := q.db.QueryRowContext(ctx, readNamespaceByName, arg.Name, arg.Owner)
	var i Namespace
	err := row.Scan(&i.ID, &i.Name, &i.Owner)
	return &i, err
}

const updateNamespace = `-- name: UpdateNamespace :exec
UPDATE namespace
SET name = ?2
WHERE id = ?1
`

type UpdateNamespaceParams struct {
	ID   string
	Name string
}

func (q *Queries) UpdateNamespace(ctx context.Context, arg UpdateNamespaceParams) error {
	_, err := q.db.ExecContext(ctx, updateNamespace, arg.ID, arg.Name)
	return err
}
