// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: operator.sql

package sqlc

import (
	"context"
)

const createOperator = `-- name: CreateOperator :exec
INSERT INTO operator (id, namespace_id, name, public_key, jwt, last_connect_time)
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
`

type CreateOperatorParams struct {
	ID              string
	NamespaceID     string
	Name            string
	PublicKey       string
	Jwt             string
	LastConnectTime *int64
}

func (q *Queries) CreateOperator(ctx context.Context, arg CreateOperatorParams) error {
	_, err := q.db.ExecContext(ctx, createOperator,
		arg.ID,
		arg.NamespaceID,
		arg.Name,
		arg.PublicKey,
		arg.Jwt,
		arg.LastConnectTime,
	)
	return err
}

const deleteOperator = `-- name: DeleteOperator :exec
DELETE
FROM operator
WHERE id = ?1
`

func (q *Queries) DeleteOperator(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteOperator, id)
	return err
}

const listOperators = `-- name: ListOperators :many
SELECT id, namespace_id, name, public_key, jwt, last_connect_time
FROM operator
WHERE namespace_id = ?1
  AND (?2 IS NULL OR id <= ?2)
ORDER BY id DESC
LIMIT ?3
`

type ListOperatorsParams struct {
	NamespaceID string
	Cursor      interface{}
	Size        int64
}

func (q *Queries) ListOperators(ctx context.Context, arg ListOperatorsParams) ([]*Operator, error) {
	rows, err := q.db.QueryContext(ctx, listOperators, arg.NamespaceID, arg.Cursor, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Operator
	for rows.Next() {
		var i Operator
		if err := rows.Scan(
			&i.ID,
			&i.NamespaceID,
			&i.Name,
			&i.PublicKey,
			&i.Jwt,
			&i.LastConnectTime,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const readOperator = `-- name: ReadOperator :one
SELECT id, namespace_id, name, public_key, jwt, last_connect_time
FROM operator
WHERE id = ?1
`

func (q *Queries) ReadOperator(ctx context.Context, id string) (*Operator, error) {
	row := q.db.QueryRowContext(ctx, readOperator, id)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.PublicKey,
		&i.Jwt,
		&i.LastConnectTime,
	)
	return &i, err
}

const readOperatorByName = `-- name: ReadOperatorByName :one
SELECT id, namespace_id, name, public_key, jwt, last_connect_time
FROM operator
WHERE name = ?1
`

func (q *Queries) ReadOperatorByName(ctx context.Context, name string) (*Operator, error) {
	row := q.db.QueryRowContext(ctx, readOperatorByName, name)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.PublicKey,
		&i.Jwt,
		&i.LastConnectTime,
	)
	return &i, err
}

const readOperatorByPublicKey = `-- name: ReadOperatorByPublicKey :one
SELECT id, namespace_id, name, public_key, jwt, last_connect_time
FROM operator
WHERE public_key = ?1
`

func (q *Queries) ReadOperatorByPublicKey(ctx context.Context, publicKey string) (*Operator, error) {
	row := q.db.QueryRowContext(ctx, readOperatorByPublicKey, publicKey)
	var i Operator
	err := row.Scan(
		&i.ID,
		&i.NamespaceID,
		&i.Name,
		&i.PublicKey,
		&i.Jwt,
		&i.LastConnectTime,
	)
	return &i, err
}

const updateOperator = `-- name: UpdateOperator :exec
UPDATE operator
SET name              = ?2,
    jwt               = ?3,
    last_connect_time = ?4
WHERE id = ?1
`

type UpdateOperatorParams struct {
	ID              string
	Name            string
	Jwt             string
	LastConnectTime *int64
}

func (q *Queries) UpdateOperator(ctx context.Context, arg UpdateOperatorParams) error {
	_, err := q.db.ExecContext(ctx, updateOperator,
		arg.ID,
		arg.Name,
		arg.Jwt,
		arg.LastConnectTime,
	)
	return err
}
