// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: operator_token.sql

package sqlc

import (
	"context"
)

const readOperatorToken = `-- name: ReadOperatorToken :one
SELECT token
FROM operator_token
WHERE operator_id = ?1
  AND type = ?2
`

type ReadOperatorTokenParams struct {
	OperatorID string
	Type       string
}

func (q *Queries) ReadOperatorToken(ctx context.Context, arg ReadOperatorTokenParams) (string, error) {
	row := q.db.QueryRowContext(ctx, readOperatorToken, arg.OperatorID, arg.Type)
	var token string
	err := row.Scan(&token)
	return token, err
}

const upsertOperatorToken = `-- name: UpsertOperatorToken :exec
INSERT INTO operator_token (operator_id, type, token)
VALUES (?1, ?2, ?3)
ON CONFLICT(operator_id, type)
    DO UPDATE SET token = excluded.token
`

type UpsertOperatorTokenParams struct {
	OperatorID string
	Type       string
	Token      string
}

func (q *Queries) UpsertOperatorToken(ctx context.Context, arg UpsertOperatorTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertOperatorToken, arg.OperatorID, arg.Type, arg.Token)
	return err
}
