// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: owner.sql

package sqlc

import (
	"context"
)

const countOwnerAccounts = `-- name: CountOwnerAccounts :one
SELECT COUNT(*) AS count
FROM account AS a
         JOIN namespace AS n ON n.id = a.namespace_id
WHERE n.owner = ? AND a.name != 'SYS'
`

func (q *Queries) CountOwnerAccounts(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerAccounts, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnerNamespaces = `-- name: CountOwnerNamespaces :one
SELECT COUNT(*) AS count
FROM namespace AS n
WHERE n.owner = ?
`

func (q *Queries) CountOwnerNamespaces(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerNamespaces, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnerOperators = `-- name: CountOwnerOperators :one
SELECT COUNT(*) AS count
FROM operator AS o
         JOIN namespace AS n ON n.id = o.namespace_id
WHERE n.owner = ?
`

func (q *Queries) CountOwnerOperators(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerOperators, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOwnerUsers = `-- name: CountOwnerUsers :one
SELECT COUNT(*) AS count
FROM "user" AS u
         JOIN namespace AS n ON n.id = u.namespace_id
WHERE n.owner = ? AND u.name != 'sys'
`

func (q *Queries) CountOwnerUsers(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countOwnerUsers, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}
