port: 5400
logger:
  level: info
  structured: true
encryptionSecretKey: "00deaa689d7b85e4a68d416678e206cb"
postgres:
  hostPort: "db:5432"
  user: postgres
  password: postgres
broker:
  natsURLs:
    - "nats://broker-node-1:5222"
    - "nats://broker-node-2:6222" # node 2 is optional (only included as a safeguard in the event that node 1 is unavailable)
