port: 6400
logger:
  level: info
  structured: true
encryptionSecretKey: "00deaa689d7b85e4a68d416678e206cb"
postgres:
  hostPort: "db:5432"
  user: postgres
  password: postgres
embeddedNats:
  hostPort: 0.0.0.0:6222
  nodeRoutes:
    - "nats://broker-node-1:5222"
