services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    user: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - example

  coro-pgtool:
    depends_on:
      db:
        condition: service_healthy
    image: corosh/coro-pgtool
    ports:
      - "5400:5400"
    command: [ "--user", "postgres", "--password", "postgres", "--host", "db", "--port", "5432", "init" ]
    networks:
      - example

  coro:
    depends_on:
      db:
        condition: service_healthy
      coro-pgtool:
        condition: service_completed_successfully
    image: corosh/coro
    ports:
      - "5400:5400"
    volumes:
      - "./config.yaml:/config.yaml:ro"
    command: [ "--service", "backend", "--config", "config.yaml" ]
    networks:
      - example

  init-operator:
    image: alpine:3.21
    depends_on:
      - coro
    volumes:
      - ../util/init-operator.sh:/init-operator.sh:ro
      - nats-config:/nats-config
    entrypoint: [ "/bin/sh", "/init-operator.sh" ]
    command: [ "http://coro:5400" ]
    networks:
      - example

  # Excluded from `example` network. Only a Coro Proxy should directly
  # communicate with a NATS server.
  nats-server:
    image: nats:2.10-scratch
    depends_on:
      init-operator:
        condition: service_completed_successfully
    command: [ "-c", "/nats-config/nats.conf" ]
    volumes:
      - nats-config:/nats-config
    ports:
      - "4222:4222"

networks:
  example:
    driver: bridge

volumes:
  nats-config: